version: '3.8'
services:
  kafka:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_OPT:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KRAFT_CONTAINER_HOST_NAME : kafka
      KRAFT_CREATE_TOPICS : topic-4,topic-3
      KRAFT_PARTITIONS_PER_TOPIC : 3
    depends_on:
      - jolokia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-network
 
  jolokia:
    image: jolokia/java-jolokia
    ports:
      - "8778:8778"
    environment:
      - JOLOKIA_AGENT_OPTS=port=8778,host=kafka,discoveryEnabled=false
    networks:
      - kafka-network
    # command: tail -f /dev/null
    
  progue-for-kafka:
    build:
      context: .
      dockerfile: dockerfile
    container_name: progue-for-kafka
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    volumes:
      - .:/src/app/
      - node_modules:/src/app/node_modules
    networks:
      - kafka-network
    command: npm run dev

volumes:
  node_modules:


networks:
  kafka-network:
    driver: bridge
